### PR TITLE
Upgrading openjdk dependency to version 8.

### PR DESCRIPTION
**Pull request by thiagohmoreira**
Hello,

For my personal needs I wanted to have a Java 8 container, and seems to me it makes sense to update your image also. Could be even better if this image had different branches for other/older versions.

### CODE REVIEW

**Comment by tboerger** [comment]
Thanks, let's see if my depending minecraft containers still work :P

**Comment by thiagohmoreira** [comment]
That is in fact exactly what I'm looking for... if/when you update the minecraft images let me know... I'm looking for 1.7.10 forge server, and found your images, they are very good for my purposes, but some mods require java 1.8.. so, to me, this will be great! Thanks in advance!

**Comment by tboerger** [comment]
The other images should be updated automatically based on this change

**Comment by thiagohmoreira** [comment]
Err.. I kind of hate to be a pain to others, but before I go and try to (re)build the images myself, seems to me that only the latest images from minecraft-vanilla and minecraft-forge were updated. All others are from 3 months ago... is this expected or an issue somewhere? I'm pretty noob in docker/dockerhub usage, so I may be missing some point here... but truth is downloading the image I'm wanting to use (not latest), even after cleaning caches and all, always give me the same java 1.7 version.

**Comment by tboerger** [comment]
Various images have been rebuilt now, thanks for the hint

**Pull request merged**
